services:
  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector:0.102.1
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8889:8889"   # Prometheus scrape for collector metrics exporter
    depends_on:
      - jaeger
      - loki

  jaeger:
    image: ghcr.io/jaegertracing/all-in-one:1.57
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # gRPC legacy
    # no volumes needed

  loki:
    image: ghcr.io/grafana/loki:2.9.8
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"

  prometheus:
    image: ghcr.io/prometheus/prometheus:v2.54.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/ampy.rules.yml:/etc/prometheus/ampy.rules.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: ghcr.io/grafana/grafana:11.2.0
    volumes:
      - ./grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ampyfin
      - GF_USERS_DEFAULT_THEME=light
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki

  promtail:
    image: ghcr.io/grafana/promtail:2.9.8
    command: ["-config.file=/etc/promtail/promtail.yaml"]
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml:ro
      - ../logs:/var/log/ampy:ro            # host logs -> container
    ports:
      - "9080:9080"                         # Promtail metrics endpoint
    depends_on:
      - loki
